FROM golang:1.19-alpine AS builder

WORKDIR /app

RUN apk update && apk add build-base

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .

ENV CGO_ENABLED=1

ENTRYPOINT go test -tags integration,sqlite_unlock_notify ./tests/integration/...