// Code generated by mockery v2.14.0. DO NOT EDIT.

package mock

import mock "github.com/stretchr/testify/mock"

// UnsafeAntiBrutServiceServer is an autogenerated mock type for the UnsafeAntiBrutServiceServer type
type UnsafeAntiBrutServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedAntiBrutServiceServer provides a mock function with given fields:
func (_m *UnsafeAntiBrutServiceServer) mustEmbedUnimplementedAntiBrutServiceServer() {
	_m.Called()
}

type mockConstructorTestingTNewUnsafeAntiBrutServiceServer interface {
	mock.TestingT
	Cleanup(func())
}

// NewUnsafeAntiBrutServiceServer creates a new instance of UnsafeAntiBrutServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUnsafeAntiBrutServiceServer(t mockConstructorTestingTNewUnsafeAntiBrutServiceServer) *UnsafeAntiBrutServiceServer {
	mock := &UnsafeAntiBrutServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
