name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
          cache: true

      - name: Download dependencies
        run: go mod download

      - name: Lint
        uses: golangci/golangci-lint-action@v3

      - name: Unit tests
        run: go test -race -count 100 ./...

      - name: Integration & End-to-end tests
        run: go test -tags integration -race -count 1 ./...

      - name: Build
        run: go build -tags=sqlite_unlock_notify -o ./bin/antibrut ./cmd/antibrut
