name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      #- name: Lint
        #uses: golangci/golangci-lint-action@v3

      #- name: Unit tests
        #run: go test -race -count 100 ./...

      - name: Integration & E2E tests
        run: go test -tags integration -race -count 1 ./...